# Main server resource pack
# Can be either a URL or a file name in the packs folder
# For URLs: "https://example.com/server-pack.zip"
# For files: "server-pack.zip"
server-pack: "server-pack.zip"

# Additional resource packs
# Can use either URLs or files from the packs folder
resource-packs:
  dungeons: "dungeons-pack.zip"
  pvp: "https://example.com/pvp-pack.zip"
  holiday: "holiday-pack.zip"