# Main server resource pack
# Can be either a URL or a file name in the packs folder
# For URLs: "https://example.com/server-pack.zip"
# For files: "server-pack.zip"
server-pack: "server-pack.zip"

# Web server settings
server-port: 40021  # Default port, can be changed to any open port on your host
localhost: false    # Set to false for production servers, true only for local testing
server-address: ""  # Will try to auto-detect if empty
fallback-address: "localhost"  # Used if auto-detection fails

# Additional resource packs
# Can use either URLs or files from the packs folder
# For URLs: "https://example.com/examplepack.zip"
# For files: "example-pack.zip"
resource-packs:
  exampleurlpack: "https://example.com/examplepack.zip"
  examplefilepack: "example-pack.zip"